// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOo7R6bj1Al0Xh8awcXn_j-zTfGCHCzTw',
    appId: '1:140484458672:web:7e0a1a5bb03d15c413a375',
    messagingSenderId: '140484458672',
    projectId: 'fir-notes-app-2a4d0',
    authDomain: 'fir-notes-app-2a4d0.firebaseapp.com',
    storageBucket: 'fir-notes-app-2a4d0.appspot.com',
    measurementId: 'G-LBRG04547P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBThA3xD6I2XMqqniwGdKrb4_adxLv4BEo',
    appId: '1:140484458672:android:e50e8187bca806bb13a375',
    messagingSenderId: '140484458672',
    projectId: 'fir-notes-app-2a4d0',
    storageBucket: 'fir-notes-app-2a4d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgew2-Io6PYJ_hLWpYMhLXGF83Y6-P4F4',
    appId: '1:140484458672:ios:89c31134f57d394713a375',
    messagingSenderId: '140484458672',
    projectId: 'fir-notes-app-2a4d0',
    storageBucket: 'fir-notes-app-2a4d0.appspot.com',
    iosBundleId: 'com.example.dbNotesApp',
  );
}
